
# Copyright (C) Igor Sysoev
# Copyright (C) Nginx, Inc.


CFLAGS =	-O2 -Ob1 -Oi -Gs $(LIBC) $(CPU_OPT)
PCREFLAGS =	-DHAVE_CONFIG_H -DPCRE_STATIC -DPOSIX_MALLOC_THRESHOLD=10 \
		-DSUPPORT_PCRE8 -DHAVE_MEMMOVE


pcre.lib:
	cd $(PCRE)

	cl -nologo -c $(CFLAGS) -I . $(PCREFLAGS) pcre_*.c

	link -lib -out:pcre.lib -verbose:lib pcre_*.obj

pcre.h:
	cd $(PCRE)/src

	copy /y pcre2.h.generic pcre2.h
	copy /y config.h.generic config.h
	copy /y pcre2_chartables.c.dist pcre2_chartables.c
